"""
Configuration file for MIH Content Automation
Generated by setup wizard
"""

import os

# API Keys
YOUTUBE_API_KEY = "AIzaSyDvnNE4cp5kJuFn1xMxBB4APamd7saFofQ"
GEMINI_API_KEY = "AIzaSyBqjvo54BMoRUTR-8PZJOMzgMfKx1kyXH0"

# OAuth Credentials File
YOUTUBE_CREDENTIALS_FILE = "youtube_credentials.json"

# Output Directory
OUTPUT_DIR = "processed_videos"

# YouTube Channels for Upload
UPLOAD_CHANNELS = [
    {
        "name": "ab",
        "id": "UCvOZdrm6eoIuOx4R3Uikt3g",
        "description": "MIH content channel 1"
    },
    {
        "name": "bc",
        "id": "UCvOZdrm6eoIuOx4R3Uikt3g",
        "description": "MIH content channel 2"
    },
    {
        "name": "cd",
        "id": "UCvOZdrm6eoIuOx4R3Uikt3g",
        "description": "MIH content channel 3"
    }
]

# Search Configuration
SEARCH_QUERIES = [
    "Linda Greenwall MIH",
    "Dr Greenwall molar incisor hypomineralisation",
    "Linda Greenwall enamel defects", 
    "Dr Greenwall pediatric whitening",
    "Linda Greenwall ICON treatment",
    "Jaz Gulati Linda Greenwall",
    "Dentistry Magazine Linda Greenwall"
]

# Processing Settings
MIN_CLIP_DURATION = 15  # seconds
MAX_CLIP_DURATION = 60  # seconds
MAX_CLIPS_PER_VIDEO = 3
AUTOMATION_INTERVAL_HOURS = 1

# Video Quality Settings
TARGET_RESOLUTION = (720, 1280)  # 9:16 aspect ratio
VIDEO_CODEC = "libx264"
AUDIO_CODEC = "aac"

# Security: Use environment variables in production
# YOUTUBE_API_KEY = os.getenv('YOUTUBE_API_KEY', YOUTUBE_API_KEY)
# GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', GEMINI_API_KEY)
